---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: dev
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "neha8888/nodejs-app:MY_NEW_TAG"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: dev
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
  resources:
    limits:
      memory: "800Mi"
      cpu: "800m"
    requests:
      memory: "600Mi"
      cpu: "400m"
